### ISSUE TITLE
Analyse pdf generation

### ISSUE THREAD

**Issue by jack-parsons** [abel-research/ampscan_webapp#6]
File prompt to change save location

**Comment by jack-parsons** [comment]
@JoshuaSteer do we need to be able to pick a reference point for this to work?

**Comment by JoshuaSteer** [comment]
Probably, again this is where I'm not exactly sure how the code works

**Comment by jack-parsons** [comment]
AmpScan MeasurementsOut method doesn't work when installed using pip
>Traceback (most recent call last):
  File "C:\Users\Jack\Documents\GitHub\ampscan_webapp\pvenv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Jack\Documents\GitHub\ampscan_webapp\pvenv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Jack\Documents\GitHub\ampscan_webapp\pvenv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Jack\Documents\GitHub\ampscan_webapp\test_app\views.py", line 315, in measurements_view
    analyse.MeasurementsOut(obj, point)
  File "C:\Users\Jack\Documents\GitHub\ampscan_webapp\pvenv\lib\site-packages\AmpScan\analyse.py", line 472, in MeasurementsOut
    return getPDF(lngth, perimeter, PolyArea, APWidth, MLWidth)  # PDF Creation function (in output.py)
  File "C:\Users\Jack\Documents\GitHub\ampscan_webapp\pvenv\lib\site-packages\AmpScan\output.py", line 44, in getPDF
    template = PdfFileReader(open(os.path.join("res", "Measurements Template.pdf"), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'res\\Measurements Template.pdf'

**Comment by JoshuaSteer** [comment]
Think that should be template = PdfFileReader(open(os.path.join("res", "Measurements Template.pdf"), "wb")) not 'rb'
